name: Test Frontend

on:
    pull_request:
        branches:
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: node:22
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright browsers
              run: npx playwright install --with-deps chromium
            - name: Clear Vite/Vitest cache
              run: rm -rf node_modules/.vite node_modules/.vitest
            - name: Run tests
              run: npm run test
